### PR TITLE
Enable Dependabot for Cargo and GitHub Actions

### PR DESCRIPTION
**Pull request by sjackman**
Enable [Dependabot](https://docs.github.com/en/code-security/dependabot) to open PRs to update dependencies.

### CODE REVIEW

**Comment by tamird** [comment]
Should this enable updating github actions as well? https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions

**Comment by sjackman** [comment]
> Should this enable updating github actions as well?

Done!

**Comment by mitsuhiko** [comment]
I worry that this just moves up the MSRV needlessly. Is there much of a point for insta to move dependencies up automatically? What would be the benefit of this?

**Comment by sjackman** [comment]
Depending on multiple versions of the same crate requires compiling that same crate multiple times, which can increase build time and executable size. One such duplicate is not such a big deal, but left unchecked, a project can easily accumulate many such duplicate dependencies.

An application that depends on `ron` 0.8 or depends on a crate that depends on `ron` 0.8, and also depends on `insta`, will now need to compile both `ron` 0.7 and 0.8. I use the tools `cargo tree --duplicates` and [`cargo deny check bans`](https://embarkstudios.github.io/cargo-deny/checks/bans/index.html#use-case---duplicate-version-detection) to prevent such duplicates.

For example when the `filter` feature of `insta` is enabled, `insta` depends on both `regex-automata` versions `0.1` and `0.4`.  As I said above, one such duplicate is not such a big deal, but many duplicates can substantially increase build time, which can be a substantial issue for large projects.
```
$ cargo update
$ cargo deny check bans |& grep duplicate
warning[duplicate]: found 2 duplicate entries for crate 'bstr'
warning[duplicate]: found 2 duplicate entries for crate 'regex-automata'
$ cargo tree --features=filters --duplicates           
regex-automata v0.1.10
└── bstr v0.2.17
    └── similar v2.3.0
        ├── insta v1.34.0
        └── similar-asserts v1.5.0
            [dev-dependencies]
            └── insta v1.34.0
regex-automata v0.4.3
└── regex v1.10.2
    └── insta v1.34.0
```

**Comment by mitsuhiko** [comment]
I understand this but that ron is not moved up is an intentional behavior because of snapshot changes. That's similar to why Insta now has it's own YAML and JSON serializers. I will close this for now until I have a better plan for RON.

**Pull request closed without merging**
