### PR TITLE
Defer glob failures

### PR DESCRIPTION
**Pull request by mitsuhiko**
This is an experimental feature to address https://github.com/mitsuhiko/insta/discussions/283

### CODE REVIEW

**Comment by JohnnyMorganz** [comment]
Thanks for the quick turnaround!
This does now continue through all snapshot failures and print out a count in the end, but it is very noisy, and it also regenerates all the snapshots (my expectation is that `cargo test` shouldn't regenerate snapshots whilst `cargo insta test` does, but that might be wrong)
image

Once it goes through all the failures it then prints out all the snapshot differences, and since there are 66 of them its a lot:
image

(Also, minor typo `failuress` at the end there)

Is it possible to make it instead print something equivalent to rusttest output (maybe behind a flag for quiet output?)
```
tests__standard@ambiguous-syntax.lua  ... ok
tests__full_moon_test_suite@anonymous-functions-2  ... FAILED

**Comment by mitsuhiko** [comment]
The default of `INSTA_UPDATE` is `auto` mode where if it's not in CI it will write new files. Try again with `INSTA_UPDATE=no` then it should not generate any changed snapshots like it would in CI.

**Comment by JohnnyMorganz** [comment]
> The default of `INSTA_UPDATE` is `auto` mode where if it's not in CI it will write new files. Try again with `INSTA_UPDATE=no` then it should not generate any changed snapshots like it would in CI.

Ah yep, that stopped it, thanks.
The main thing is just the noisy "snapshot differences" section still, a quieter overview would be awesome.

Also, just a side note, since its not failing on first snapshot error, `cargo test` can take a little bit longer (2s vs 7s when keep going). It doesn't really matter to me, but it may be inconvenient for others.

**Comment by mitsuhiko** [comment]
It might be interesting to couple it with the failfast option of rusttest. That way it aligns with what users might already use. Will give that a whirl.

**Comment by mitsuhiko** [comment]
Turns out that the fail fast flag is only passed to the cargo wrapper so I won't be able to access this. Adding another flag to envvars is unlikely to be discoverable. I will try around with this a bit.

**Pull request merged**
