### PR TITLE
cargo-insta: allow multiple --exclude flags

### LINKED ISSUE #519: cargo-insta: exclude flag doesn't take multiple arguments
### What happened?

I ran my test with multiple exclude flags. 

### Reproduction steps

`cargo insta test --workspace --all-targets --exclude a --exclude b`

```
error: The argument '--exclude <SPEC>' was provided more than once, but cannot be used multiple times

USAGE:
    cargo insta test --all-targets --exclude <SPEC> --test-runner <test-runner> --unreferenced <unreferenced> --workspace

For more information try --help
```

### Insta Version

cargo-insta 1.39.0

### rustc Version

_No response_

### What did you expect?

I expected it to behave like cargo test: 

>--exclude SPEC…
>Exclude the specified packages. Must be used in conjunction with the --workspace flag. **This flag may be specified multiple times** and supports common Unix glob patterns like *, ? and []. However, to avoid your shell accidentally expanding glob >patterns before Cargo handles them, you must use single quotes or double quotes around each pattern.

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #519

### CODE REVIEW

**Comment by max-sixty** [comment]
LGTM, thanks for the PR

(Will wait for @mitsuhiko to merge)

**Comment by max-sixty** [comment]
@ajwerner could you merge `master` in to fix the clippy error? Then I'll merge

**Comment by ajwerner** [comment]
> @ajwerner could you merge `master` in to fix the clippy error? Then I'll merge
> 
> `+ feel free to add a note in the changelog

Done.

**Comment by max-sixty** [comment]
Thanks @ajwerner !

**Pull request merged**
