### PR TITLE
Improve development experience

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I'm not entirely opposed to this change, but in the past I decided intentionally against it so I can end up with different `.lock` files for insta and cargo-insta due to different MSRV support.

**Comment by max-sixty** [comment]
> end up with different `.lock` files for insta and cargo-insta due to different MSRV support.

FWIW for dependencies that are only part of `cargo-insta`, having the crates as a workspace won't affect MSRVs. We do this in PRQL, where the CLI can be on latest but the library follows debian.

(but maybe the dependencies are overlapping...)

I do think a workspace is a much nicer development experience.

**Comment by tamird** [comment]
@mitsuhiko I don't quite understand the concern. Wouldn't the .lock file only be published for cargo-insta, not for insta? That's my understanding of the usual convention.

**Comment by max-sixty** [comment]
> @mitsuhiko I don't quite understand the concern. Wouldn't the .lock file only be published for cargo-insta, not for insta? That's my understanding of the usual convention.

There is only a single `Cargo.lock` file for a workspace. Unless I'm really mistaken — currently the `cargo-insta/Cargo.lock` file does nothing. And we should remove it.

**Comment by tamird** [comment]
That's right. I removed it. But my point was that the Cargo.lock should not be published with the insta library, only the cargo-insta CLI.

**Comment by tamird** [comment]
Ah, I see what you mean now. Indeed this change means that the versioning restrictions that apply to `insta` will also apply to `cargo-insta`.

**Comment by tamird** [comment]
Ugh, this changed the current directory when the integration tests run, and they are not resilient to this. I'll wait for #412 to land first.

**Comment by max-sixty** [comment]
> Ah, I see what you mean now. Indeed this change means that the versioning restrictions that apply to `insta` will also apply to `cargo-insta`.

Yes cool. Still a big fan of the change!

Do you think we can still get `1.61` tests to pass?

**Comment by tamird** [comment]
Yeah, they were passing before I split out #412.

**Comment by mitsuhiko** [comment]
FWIW I would prefer a workspace as well. I think the way it could be accomplished might be with manually maintaining a secondary `Cargo.lock` file and move it over in the tests. I am doing something similar for a `Cargo.lock.msrv` file in some libraries. Eg.: https://github.com/mitsuhiko/similar

**Comment by max-sixty** [comment]
Re the MSRV — FWIW in PRQL we use [`cargo msrv verify`](https://github.com/foresterre/cargo-msrv) in [our CI](https://github.com/PRQL/prql/blob/60d93e0a0429f5b1e410069e947c0185700d876b/.github/workflows/tests.yaml#L464-L483), which verifies that that the package is valid with its specified MSRV (e.g. [here](https://github.com/PRQL/prql/blob/main/crates/prql-compiler/Cargo.toml#L11)).

It allows different MSRVs by crate.

Relative to maintaining another `Cargo.lock.msrv`, it requires another dev dependency, but it has worked quite well for us over the past year.

**Comment by tamird** [comment]
Alright I've abandoned the virtual manifest for now. Instead I added cargo-insta and its integration tests to the root manifest workspace.

**Comment by tamird** [comment]
At long last this is green.

**Comment by mitsuhiko** [comment]
Validated: the lock file is handled correctly by `cargo package`.

**Comment by max-sixty** [comment]
> That won't work here because MSRV is 1.51 but the tests also need to run against 1.61.

FYI this isn't how `cargo msrv` works — check out the PRQL workflows if you're interested to learn more.

Thanks for this PR!

**Pull request merged**
