### PR TITLE
Deprecate `--no-force-pass`

### PR DESCRIPTION
**Pull request by max-sixty**
This seems like a confusing name, and is dominated by the much clearer `--check`

### CODE REVIEW

**Comment by max-sixty** [comment]
Clears up any confusion from #512

**Comment by mitsuhiko** [comment]
I'm okay with that, but it's confusing that the underlying envvar that drives the feature is called `INSTA_FORCE_PASS`. Will this not cause further confusion?

**Comment by max-sixty** [comment]
> I'm okay with that, but it's confusing that the underlying envvar that drives the feature is called `INSTA_FORCE_PASS`. Will this not cause further confusion?

Because the option in `cargo insta` is `--check` but the env var in `insta` is `INSTA_FORCE_PASS`?

I don't think they necessarily have to correspond 1:1 — `cargo  insta` is a higher level UX, and `--check` does a couple of other things. So I see `INSTA_FORCE_PASS` as mostly an internal way for `cargo-insta` to say "we're handling failures at the end; keep going `insta`".

If you feel strongly then we could hide that option while still allowing it. Or some other alternative? But as #512 demonstrates I don't think the existing state is a nice clear interface...

**Comment by mitsuhiko** [comment]
I think it might be fine to just say `--check` is the way to go.

**Comment by max-sixty** [comment]
> I think it might be fine to just say `--check` is the way to go.

OK, interpreting this to mean you're good with hiding `--no-force-pass`. Let me know (+ apologies for misunderstanding) if that's not correct!

**Pull request merged**
