### PR TITLE
Use full module path for test names

### PR DESCRIPTION
**Pull request by max-sixty**
Closes https://github.com/mitsuhiko/insta/issues/78

Is this the right design? A good case is the `insta__test__embedded.snap` change below. I suspect those cases are rare; though it's a breaking change where they do exist.

I need to adds a whatsnew

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Something went wrong here

**Comment by imsnif** [comment]
Hey @mitsuhiko + @max-sixty, just a heads up: this introduced a breaking change. When upgrading insta, the old snapshots were not converted to the new format.

Not terrible, of course - it just required a bulk rename. Wanted to let you know so that maybe you'd like to document this somewhere or make insta "do the right thing" if it finds snapshots from the "old" mode.

Anyway, thanks very much for insta. It's been invaluable for me in various projects.

**Comment by max-sixty** [comment]
@imsnif thanks. 

Do you have an example of a change in the snapshot format? This is some time ago so my memory is foggy, and I don't see any changes to our existing tests as part of this PR.

**Comment by imsnif** [comment]
Hey @max-sixty, sure.

What happened is that the snapshot file names changed for us. So we had to do a bulk rename. You can see the exact details of the name change in this comment: https://github.com/imsnif/diskonaut/pull/25#issuecomment-646106391

**Comment by max-sixty** [comment]
Thanks a lot for the full description!

Was `cargo-insta test --force-update-snapshots` tried? That would have updated all snapshots, though (IIRC) not deleted the old ones. I've thought of that as an escape hatch for otherwise burdensome changes.

**Comment by imsnif** [comment]
Indeed did not know about it, but to be fair I didn't look too closely. :) Thanks!

**Pull request merged**
