### PR TITLE
Fix #56

### PR DESCRIPTION
**Pull request by max-sixty**
Between the whitespace PR and https://github.com/mitsuhiko/insta/pull/56, I combine incompatible code. Shouldn't have left out the tests!

Now fixed. I also hand-tested an Accept for an inline test

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Also since I have you: i fixed a regression here which caused the serialization system to change which made cargo-insta incomaptible with non master builds.

**Comment by max-sixty** [comment]
OK great - apologies assuming that was me. I can't see the break though - the changes I see there are a) changing `SnapshotContents` to a tuple struct and b) making the `SnapshotContents` field private. 
Where was the regression? Anything I can do here to confirm a fix with a test?

**Comment by max-sixty** [comment]
(also any other ideas for features / stuff to work on - I think this library is awesome. I have more time & interest atm than I have ideas for features)

**Comment by mitsuhiko** [comment]
`SnapshotContents` is serialized to disk. So the change i merged earlier changed the disk serialization format causing cargo review to fail when it used data created from earlier insta versions.

**Pull request merged**
